platform :ios, '13'
use_modular_headers!

target 'GuiKitExample' do
  pod 'ActionSheet.swift', :path => '../'
  pod 'HUD.swift', :path => '../'
  pod 'SectionsTableView.swift', :path => '../'
  pod 'UIExtensions.swift', :path => '../'
  pod 'Chart.swift', :path => '../'
  pod 'ThemeKit.swift', :path => '../../component-kit-ios/'
end

target 'GuiKitTests' do
  pod 'ActionSheet.swift', :path => '../'
  pod 'HUD.swift', :path => '../'
  pod 'SectionsTableView.swift', :path => '../'
  pod 'UIExtensions.swift', :path => '../'
  pod 'Chart.swift', :path => '../'
end
